# Generated by Django 5.2.8 on 2025-11-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetflixTitles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_id", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                ("director", models.CharField(max_length=100)),
                ("cast", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("date_added", models.CharField(max_length=255)),
                ("release_year", models.IntegerField()),
                ("rating", models.CharField(max_length=15)),
                ("duration", models.CharField(max_length=50)),
                ("listed_in", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=255)),
            ],
        ),
    ]
